const FETCH_DAILY_DATA_REQUEST = "FETCH_DAILY_DATA_REQUEST";
const FETCH_DAILY_DATA_SUCESS = "FETCH_DAILY_DATA_SUCESS";
const FETCH_DAILY_DATA_FAILURE = "FETCH_DAILY_DATA_FAILURE";

export {
  FETCH_DAILY_DATA_REQUEST,
  FETCH_DAILY_DATA_SUCESS,
  FETCH_DAILY_DATA_FAILURE,
};
