const FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST";
const FETCH_DAILY_COUNTRIES_SUCESS = "FETCH_DAILY_COUNTRIES_SUCESS";
const FETCH_DAILY_COUNTRIES_FAILURE = "FETCH_DAILY_COUNTRIES_FAILURE";

export {
  FETCH_COUNTRIES_REQUEST,
  FETCH_DAILY_COUNTRIES_SUCESS,
  FETCH_DAILY_COUNTRIES_FAILURE,
};
