const FETCH_COUNTRY_REQUEST = "FETCH_COUNTRY_REQUEST";
const FETCH_COUNTRY_SUCESS = "FETCH_COUNTRY_SUCESS";
const FETCH_COUNTRY_FAILURE = "FETCH_COUNTRY_FAILURE";

export { FETCH_COUNTRY_REQUEST, FETCH_COUNTRY_SUCESS, FETCH_COUNTRY_FAILURE };
